### ISSUE TITLE
You have various bugs

### ISSUE THREAD

**Issue by Qussiro** [Sylphri/expression-evaluator#1]
![image](https://user-images.githubusercontent.com/42040503/218265831-fda5203d-29fc-4c26-941a-9770280f40e5.png)

![image](https://user-images.githubusercontent.com/42040503/218265820-a2041fe5-bd22-4822-98ad-97dd4f31c603.png)

![image](https://user-images.githubusercontent.com/42040503/218265850-60b9d272-b7d7-4867-8c8a-8f86a29ffb7c.png)

![image](https://user-images.githubusercontent.com/42040503/218265856-befa29bb-e5d8-459f-8f33-786d2971f0c1.png)

**Comment by Sylphri** [comment]
Yes

сб, 11 февр. 2023 г. в 17:08, Qussiro ***@***.***>:

**Comment by Qussiro** [comment]
U r dead

сб, 11 февр. 2023 г. в 17:28, Sylphri ***@***.***>:

**Comment by Norixum** [comment]
Thanks for your feedback. I fixed this bugs in last commit.
